src/main/java/org/apache/fineract/api/BeneficiaryApi.java, src/main/java/org/apache/fineract/api/IMUConversionApi.java, src/main/java/org/apache/fineract/api/OperationsDetailedApi.java, src/main/java/org/apache/fineract/data/IMUConversionData.java, src/main/java/org/apache/fineract/operations/Beneficiary.java, src/main/java/org/apache/fineract/operations/BeneficiaryRepository.java, src/main/java/org/apache/fineract/operations/CurrencyRate.java, src/main/java/org/apache/fineract/operations/CurrencyRateRepository.java, src/main/resources/sql/migrations/tenant/V27__currency_rate_master.sql, src/main/resources/sql/migrations/tenant/V28__beneficiary_list.sql
PR consists of:
- Beneficiary APIs
- IMU Conversion APIs
- Operation Detailed API to show PartyId and PartyIdType
=> Beneficiary, Currency Lock and Transfer Detail API

src/main/java/org/apache/fineract/api/BatchApi.java
This PR includes the below updates
1. Removed AtomicRefernce from `generateDetails` function.
2. Code optimization.
=> Code enhancement in reportGenerating logic for bulk

src/main/java/org/apache/fineract/operations/Batch.java, src/main/resources/sql/migrations/tenant/V38__add_amount_fields_in_batches.sql
1. Updated `batches` table with txn amount-related fields.
2. Added migration script for above changes in mysql table.
=> Updated batches table to support transaction amount related fields

src/main/java/org/apache/fineract/api/BatchApi.java, src/main/java/org/apache/fineract/operations/BatchSpecs.java
Updates
1. Updated batch details API to support `command=download` for downloading CSV.
2. Implemented new API /batches for getting the list of batches in a paginated manner. (NOT TESTED)
=> Batch details updated

src/main/java/org/apache/fineract/api/BatchApi.java, src/main/java/org/apache/fineract/operations/Batch.java, src/main/java/org/apache/fineract/operations/BatchDTO.java, src/main/resources/sql/migrations/tenant/V39__add_mode_field_in_batches.sql
Updates in this PR
1. Multiple fields are renamed in `BatchDTO.java` to sync with API spec.
2. New field added in `batches` table `PAYMENT_MODE`.
=> Updated Batch API to match specs

build.gradle, src/main/java/org/apache/fineract/ServerApplication.java, src/main/java/org/apache/fineract/api/BatchApi.java, src/main/java/org/apache/fineract/config/PaymentMode.java, src/main/java/org/apache/fineract/config/PaymentModeConfiguration.java, src/main/java/org/apache/fineract/operations/Variable.java, src/main/java/org/apache/fineract/operations/VariableRepository.java, src/main/resources/application.yml
Updates in this PR
1. Added Payment mode configuration in `application.yaml`.
2. Updated the report generation to fix the 2x data calculation for batch summary.
3. Added `lambok` for auto-generation of boilerplate code in configuration POJO.
=> Fixes 2x data in report generation logic

src/main/java/org/apache/fineract/api/BatchApi.java
Updates in this PR
1. Hack to make batchSummary API work with older batch API.
Refer this PR https://github.com/openMF/ph-ee-bulk-processor/pull/39
=> Batch summary fix

build.gradle, src/main/java/org/apache/fineract/ServerApplication.java, src/main/java/org/apache/fineract/api/BatchApi.java, src/main/java/org/apache/fineract/api/BeneficiaryApi.java, src/main/java/org/apache/fineract/api/ErrorCodesCRUDApi.java, src/main/java/org/apache/fineract/api/IMUConversionApi.java, src/main/java/org/apache/fineract/api/OperationsApi.java, src/main/java/org/apache/fineract/api/OperationsDetailedApi.java, src/main/java/org/apache/fineract/api/PermissionsApi.java, src/main/java/org/apache/fineract/api/RolesApi.java, src/main/java/org/apache/fineract/api/UsersApi.java, src/main/java/org/apache/fineract/config/AuthorizationServerConfig.java, src/main/java/org/apache/fineract/config/WebSecurityConfiguration.java, src/main/java/org/apache/fineract/core/service/TenantAwareHeaderFilter.java, src/main/resources/application.yml, src/main/resources/sql/migrations/tenant/V40__add_empty_encoded_string_in_oauth_client_details.sql
* Added spring boot dependency management.
* Updated APIs with the version upgrade of spring boot.
* Added web security configuration to enable swagger UI and enable authentication in swagger UI.
* Enabled swagger authentication in APIs 
* Added migration script for change required in DB.
* https://docs.google.com/document/d/1U3mbsj99NegRjjbCrtcwjhXRQ0H6ld3zwXwL_EiV4bU/edit?usp=sharing
=> Enabled swagger documentation

src/main/java/org/apache/fineract/api/OperationsDetailedApi.java, src/main/java/org/apache/fineract/operations/TransactionRequest.java, src/main/resources/sql/migrations/tenant/V42__add_error_information_in_transaction_request_table.sql
* Added migration script for adding `ERROR_INFORMATION` field in transaction_request table.
=> Added migration script for error_info column in txn_request table

build.gradle, src/main/java/org/apache/fineract/ServerApplication.java, src/main/resources/application.yml
* Integrated JsonWebSignature support.
* New configuration for enabling and disabling JWS,
```yaml
security:
jws:
enable: false
``` 
PS:  Disabled by default.
=> Integrated JsonWebSignature support

src/main/java/org/apache/fineract/api/BatchApi.java, src/main/java/org/apache/fineract/operations/BatchDTO.java
Addresses: [GOV-250](https://mifosforge.jira.com/browse/GOV-250)
Related : https://github.com/openMF/ph-ee-connector-integration-test/pull/39
[GOV-250]: https://mifosforge.jira.com/browse/GOV-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOV-250: Detects batch failure rates

src/main/java/org/apache/fineract/api/OperationsDetailedApi.java, src/main/java/org/apache/fineract/utils/DateUtil.java, src/main/resources/application.yml, src/main/resources/sql/migrations/core/V2__tenant-server-connections.sql
Jira Ticket : https://mifosforge.jira.com/browse/GOV-264
_(Ignore if these details are present on the associated JIRA ticket)_
=> [GOV - 264]Changing custom date time to UTC format

.circleci/config.yml
(https://mifosforge.jira.com/browse/GOV-527) Description
* Added CircleCI to build and push the docker image to Dockerhub 
* Add a link to the design document or include the design bullet points related to this PR here.
_(Ignore if these details are present on the associated JIRA ticket)_
=> #GOV-527 Build and Push the Docker Image to Dockerhub 

.circleci/config.yml, build.gradle, src/main/java/org/apache/fineract/operations/TransactionRequestRepository.java
Changed the pipeline for openjdk v13
Changed connector common version
https://fynarfin.atlassian.net/browse/PHEE-377?atlOrigin=eyJpIjoiM2RlYzIxODRkOGNkNGYzZTkwNDZjY2MyNTc4ODRmZWYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
_(Ignore if these details are present on the associated JIRA ticket)_
=> [PHEE-377] jdk version update

.circleci/config.yml
Add authentication credentials for docker in docker executor in circle-ci config file
=> Add auth credentials for docker-executor

.circleci/config.yml
[PHEE-386 Update circle CI config of micro services with integration test](https://fynarfin.atlassian.net/browse/PHEE-386?atlOrigin=eyJpIjoiZjczZjdlOWI5MTA1NDgyN2I3OTQ4M2NiMzk5ZTVkMGYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[PHEE-373 build & host ph-ee-engine chart, g2p-sandbox chart and G2P sand…](https://fynarfin.atlassian.net/browse/PHEE-373?atlOrigin=eyJpIjoiYmVjYTRkYWEyNmMxNGIyNWI2ODk5OTI3OGMxMTdjODYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-386,373 Update circle CI config of with integration test and host charts

src/main/java/org/apache/fineract/api/OperationsDetailedApi.java, src/main/java/org/apache/fineract/operations/TransferSpecs.java, src/main/java/org/apache/fineract/operations/TransferStatusCheck.java
Implements [GOV-158](https://mifosforge.jira.com/browse/GOV-158)
Design Specification are as follows:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-da5021f9-7fff-d3d7-233f-35cb1cede1f2"><ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:decimal;font-size:12pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 18pt;" aria-level="3"><h3 dir="ltr" style="line-height:1.295;text-align: justify;margin-top:2pt;margin-bottom:0pt;" role="presentation"><span style="font-size:12pt;font-family:Calibri,sans-serif;color:#000000;background-color:transpar …
=> GOV-158:PaymentStatusCheck API

src/main/java/org/apache/fineract/api/BatchApi.java
Includes fix for wrong batch txn count after batch aggregation.
=> Fix for batch processing

src/main/java/org/apache/fineract/api/BatchApi.java
This fixes regression caused by https://github.com/openMF/ph-ee-operations-app/pull/67
Part of : https://github.com/openMF/ph-ee-integration-test/pull/132
_(Ignore if these details are present on the associated JIRA ticket)_
=> GOV-302 Fix for null pointer in fix for GOV-302:Async file validation test case

build.gradle, src/main/java/org/apache/fineract/api/BatchApi.java, src/main/resources/application.yml
[GOV-359](https://mifosforge.jira.com/browse/GOV-359)
[GOV-359]: https://mifosforge.jira.com/browse/GOV-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOV-359: Create batch aggregate api

src/main/java/org/apache/fineract/api/OperationsApi.java, src/main/java/org/apache/fineract/operations/BusinessKey.java, src/main/java/org/apache/fineract/operations/Task.java, src/main/java/org/apache/fineract/operations/TaskRepository.java, src/main/java/org/apache/fineract/operations/TransactionRequestRepository.java, src/main/java/org/apache/fineract/operations/Transfer.java, src/main/java/org/apache/fineract/operations/TransferRepository.java, src/main/java/org/apache/fineract/operations/TransferResponse.java, src/main/java/org/apache/fineract/operations/Variable.java, src/main/java/org/apache/fineract/operations/VariableRepository.java
[PHEE-453 Ops-app dpg version](https://fynarfin.atlassian.net/browse/PHEE-453?atlOrigin=eyJpIjoiNzRiMGYzYzRmODkyNGNjZWFiOTg1ZDFmZjllYmFhMzIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-453 Ops-app dpg version

src/main/java/org/apache/fineract/api/OperationsApi.java, src/main/java/org/apache/fineract/operations/TransferRepository.java
[PHEE-486 Ops app api to fetch list of variable by transaction id](https://fynarfin.atlassian.net/browse/PHEE-486?atlOrigin=eyJpIjoiNGYwNzFlMDJlOTdlNGFlZDgwOGZiYjYzMTk2YjM1MTUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-486] Ops app api to fetch list of variable by transaction id

src/main/java/org/apache/fineract/api/OperationsApi.java, src/main/java/org/apache/fineract/operations/TransactionRequestRepository.java
[PHEE-498 Update Ops app variable API to check transaction ID in transactionRequest](https://fynarfin.atlassian.net/browse/PHEE-498?atlOrigin=eyJpIjoiNTBhYmRjNzU5YTk2NGJhMWIzMTA4NTQzY2FkYmFjNmIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-498] Update Ops app variable API to check transaction ID in transactionRequest table also

src/main/java/org/apache/fineract/api/BatchApi.java, src/main/java/org/apache/fineract/operations/BatchDTO.java
[PHEE-494 Add Minio to the ph ee engine helm chart](https://fynarfin.atlassian.net/browse/PHEE-494?atlOrigin=eyJpIjoiZjQ4MjNhZmJmZTdlNDEyZGJhNTAyYzE0MjcyZjkwMWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-494]change naming convention to camelcase

.circleci/config.yml, Dockerfile, build.gradle, src/main/java/org/apache/fineract/service/UtilityServiceImpl.java
[PHEE-624 Update sha algorithm, java version 8 -> 11 operations app](https://fynarfin.atlassian.net/browse/PHEE-624?atlOrigin=eyJpIjoiYjE5NGZhNGZkNTg0NGY1MWIyZGRlYzJiZTMxOGYyYmQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-624] Update sha algorithm, java version 8 -> 11 operations app

src/main/java/org/apache/fineract/operations/TransferStatus.java
[PHEE-636 Fix operation app GET transfers API 500 error.](https://fynarfin.atlassian.net/browse/PHEE-636?atlOrigin=eyJpIjoiZGUzYjI5ODliOWE2NGNlNmE3OTU5YWVmMzcwZjE4NWMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-636] Fix operation app GET transfers API 500 error.

src/main/java/org/apache/fineract/operations/TransactionRequestState.java
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.
=> [PHEE-660] Add enum in transaction request

src/main/java/org/apache/fineract/api/BatchApi.java, src/main/java/org/apache/fineract/operations/TransferRepository.java
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.
=> [PHEE-660] Batch Detail API fix

src/main/resources/sql/migrations/tenant/V22__password_validation_policy.sql
[PHEE-720 update migrations scripts and mysql connector for version 8](https://fynarfin.atlassian.net/browse/PHEE-720?atlOrigin=eyJpIjoiZGMwNmRiODk2ZTExNGE2Yzg3NTFiZWJiNzhkMjEzNjMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-720] update migrations scripts and mysql connector for version 8
